### ISSUE TITLE
Evaluation codes

### ISSUE THREAD

**Issue by ShihuaHuang95** [HelenMao/MSGAN#1]
Hi, thanks for such excellent work. I am wondering if you would like to make the evaluation codes that you use available publicly?

**Comment by HelenMao** [comment]
Hi, thanks for your interest in our work. All the evaluation codes we use are from the corresponding official version, and we provide the links in the appendix of our paper.

**Comment by ShihuaHuang95** [comment]
Yes, I see that, thanks for your reply!
