### ISSUE TITLE
Questions about DRIT

### ISSUE THREAD

**Issue by Yitian-Li** [HelenMao/MSGAN#10]
Hello，Thanks for sharing the great work!  I would like to ask some questions since I think DRIT is kind of hard for me.

Num1: What does fake_B_encoded、fake_B_random and fake_AA_encoded respectively mean? In other words, what is the mean of output_fakeA of generators? (model.py line 153)

Num2: I have trained my DRIT model using cat2dog dataset under default train options for 1000 epochs , I think maybe it's time to test. So I test my model by
 `python test.py --dataroot ./datasets/cat2dog --resume ./results/trial/00979.pth` 
and get 5 dogs images per folder. But the 5 dogs looks all same, the only difference is color. Does that mean mode collapse occur or I test my model in a wrong way? How can I get the results like your "Example Results"？

Num3: How can I calculated scores such as FID or LPIPS?

Thanks again!

**Comment by Yitian-Li** [comment]
For question2, here are some image of my test results. 
input:
![input](https://user-images.githubusercontent.com/48313312/64943569-a9665880-d89e-11e9-8abe-542c8e7a73c7.png)
output 0-4:
![output_0](https://user-images.githubusercontent.com/48313312/64943574-ad927600-d89e-11e9-8707-ab70190f9c4e.png)
![output_1](https://user-images.githubusercontent.com/48313312/64943579-af5c3980-d89e-11e9-85ed-47aab9ea71e5.png)
![output_2](https://user-images.githubusercontent.com/48313312/64943580-b08d6680-d89e-11e9-9000-38a1217c4ab0.png)
![output_3](https://user-images.githubusercontent.com/48313312/64943583-b2572a00-d89e-11e9-94e5-85593a2446b9.png)
![output_4](https://user-images.githubusercontent.com/48313312/64943586-b3885700-d89e-11e9-9f75-1a5afc28ed06.png)

**Comment by HelenMao** [comment]
Hi sorry for the late reply.
1. For your question about DRIT, I suggest reading their paper [DRIT](https://arxiv.org/abs/1808.00948) first to get more details.
The fake_B_encoded is the generated image using encoded latent vector z from A domain.
The fake_B_random  is the generated image using random noise vector z from A domain.
The fake_AA_encoded is the self-reconstructed image using encoded latent vector z from domain A.
2. We use 1999 epochs when training cat2dog in DRIT and MSGAN.
3. Please see the links in Quantitative Evaluation Metrics at the bottom of our Github project. And also see the appendix carefully in our paper.
