### ISSUE TITLE
where is the appendix of the paper?

### ISSUE THREAD

**Issue by jiaying96** [HelenMao/MSGAN#12]
I found the appendix in arXiv:1903.05628v6.
I do not understand the following sentence:For LPIPS, we randomly select 50 pairs of the 50 images of each context in the test set to compute LPIPS and average all the values for this trial.

What's the meaning of 50 pairs ? for one pair, the two picture is ?
There are three way to calculate LPIPS,use way 2 or way 3?
```
way 1:python compute_dists.py -p0 imgs/ex_ref.png -p1 imgs/ex_p0.png --use_gpu
way 2:python compute_dists_dirs.py -d0 imgs/ex_dir0 -d1 imgs/ex_dir1 -o imgs/example_dists.txt --use_gpu
way 3:python compute_dists_pair.py -d imgs/ex_dir_pair -o imgs/example_dists_pair.txt --use_gpu
```

**Comment by HelenMao** [comment]
Hi, for each test context (condition), we generate its corresponding 50 images given this context. Then we randomly choose 2 images of these 50 images to form one pair, and we select 50 pairs. We calculate LPIPS from these chosen 2 images in one pair, which are the results of using the same condition. You can modify the codes according to the above illustration.

**Comment by korawat-tanwisuth** [comment]
Hi Helen @HelenMao,

I was able to reproduce your result for LPIPS if I don't normalize the image to the range [-1,1], which I am supposed to. Could you please let me know if you normalize the image first before calling the function? Thank you for your response!
