### ISSUE TITLE
Minor mode collapse problems

### ISSUE THREAD

**Issue by GrepRunRepeat** [HelenMao/MSGAN#13]
Hello,

thanks for your awesome proposal to the mode collapse problem! I combined the MS-GAN with the GAN-CLS (https://github.com/Yoan-D/exploring-text-to-image-synthesis-with-conditional-GANs)
and got reasonable results training on the caltech bird-dataset but I still had **minor** mode collapse problems. Did you also experience similar problems during training, for example with the Stackgan?

**Comment by Yoan-D** [comment]
Issue

**Comment by HelenMao** [comment]
Hi, the mode-seeking loss can help the **baseline** to alleviate the mode collapse problem and may have good results when modifying the lambda in a proper way.

**Comment by GrepRunRepeat** [comment]
Ok thanks then I will try fine-tuning the lamba.
