### ISSUE TITLE
NBD and JSD

### ISSUE THREAD

**Issue by mxkai** [HelenMao/MSGAN#14]
Hi,thank you for your excellent work and providing the code links of evaluation，but I don't know how to use NDB in other datasets and find no JSD, can you provide the NBD and the JSD codes of the evaluation Facade and Map

**Comment by HelenMao** [comment]
Hi, you can see the codes in this file: gans-n-gmms/utils/ndb.py
They report JSD directly as JS.
We just use this code by taking their eval example as a reference.
