### ISSUE TITLE
Mode Seeking Loss does not decrease 

### ISSUE THREAD

**Issue by weixiong-ur** [HelenMao/MSGAN#16]
Hi,
I used your loss in my own code on my own dataset using a pix2pix model. When using only the gan loss and l1 loss, the model is trained well. However, when adding the ms loss to the generator, the ms loss does not decrease and the whole training crashes. I tried different ms loss lambda, but all failed. Have you encountered such issues during training? Are there any possible reasons for this problem? Thank you.

**Comment by HelenMao** [comment]
Hi, could you give me more details about your dataset? 
Also, you can add some losses, such as the feature matching loss and perceptual loss, to stabilize the training.
