### ISSUE TITLE
compute <mode seeking loss> is different from paper!

### ISSUE THREAD

**Issue by Johnson-yue** [HelenMao/MSGAN#2]
https://github.com/HelenMao/MSGAN/blob/88c86ee63f14e43134a08bcee53fbf020ad33c82/DCGAN-Mode-Seeking/model.py#L72
https://github.com/HelenMao/MSGAN/blob/88c86ee63f14e43134a08bcee53fbf020ad33c82/DCGAN-Mode-Seeking/model.py#L73

https://github.com/HelenMao/MSGAN/blob/88c86ee63f14e43134a08bcee53fbf020ad33c82/DCGAN-Mode-Seeking/model.py#L75

Hi, thank you sharing the code of paper <MS-GAN>,  and I have a question about your mode seeking loss  **lz** in code. 

In your paper ,the format is :  
 
![image](https://user-images.githubusercontent.com/10268274/54797408-020dbd80-4c8f-11e9-85ef-53a9d1f1b33c.png)
 but in your code DCGAN, [ **lz**](https://github.com/HelenMao/MSGAN/blob/88c86ee63f14e43134a08bcee53fbf020ad33c82/DCGAN-Mode-Seeking/model.py#L72)  it is reciprocal with paper， why ？

**Comment by HelenMao** [comment]
Hi, thanks for your interest in our work. Our motivation lies in maximizing the ratio. However,  in the implementation, to be consistent with the optimizer of the original loss of G (we minimize the loss of G), we minimize the reciprocal of the ratio. This has the same effect.

**Comment by Johnson-yue** [comment]
Oh，Thank your reply，I understand it now！
