### ISSUE TITLE
Gradient-based mode seeking loss

### ISSUE THREAD

**Issue by skmhrk1209** [HelenMao/MSGAN#3]
Hi, thanks for sharing the code of the paper.
Have you tried gradient-based mode seeking loss as below?

![CodeCogsEqn](https://user-images.githubusercontent.com/29158616/55077821-06493900-50dc-11e9-9527-a673f1a86d83.png)

In conditional image generation task on the CIFAR-10, I got almost the same FID with gradient-based mode seeking loss as the one with original distance-based mode seeking loss.

**Comment by HelenMao** [comment]
Hi, thanks for your interest in our work. I think your version of the gradient-based mode seeking loss is the square of our original distance-based mode seeking loss with the original L1 distance choice. Therefore, the tendency is similar.
Our distance-based mode seeking loss can be regarded as the gradient-based one if we choose the L1 distance.

**Comment by skmhrk1209** [comment]
Got it. Thanks for your reply!
