### ISSUE TITLE
help needed for reproducing FID

### ISSUE THREAD

**Issue by youngjung** [HelenMao/MSGAN#4]
Hi, thanks for making your work publicly.

I would like to build my idea upon your nice work but running your DCGAN train/test code as it is did not give me similar FID scores while the images (gen_00199.jpg) look fine.
![image](https://user-images.githubusercontent.com/45905238/56343598-26a97680-61f6-11e9-8495-16749a731695.png)

airplane 67.26209697186295
automobile 56.615038948216466
bird 67.71981481266164
cat 64.21582516792154
deer 50.58379969002419
dog 74.1233251819657
frog 55.22868149492308
horse 60.88559157869355
ship 52.45243167542941
truck 52.44226222359282
fid: 60.15288677452914 +_ 7.530598089037249

Testing with your pretrained weights results in better but still not there.
airplane 55.98297725079635
automobile 48.51736857887687
bird 62.36735954146019
cat 54.30139778488274
deer 50.4328713386401
dog 68.39370845428152
frog 47.34936598559659
horse 54.073287595819295
ship 47.548950778636936
truck 48.33605156842515
fid: 53.73033388774157 +_ 6.6423165837502305

Could you find something wrong in my procedure below?
- Train
`python train.py --dataroot ~/data/cifar10`
- Test
`python test.py --dataroot ~/data/cifar10 --resume results/trial/00199.pth --num 5000 --name trial/images_test`
- Prepare training images
`python cifar10_to_imagefolder.py --dir_dataset ~/data/cifar10/ --dir_dest ~/data/cifar10/images/train`
- Prepare per-class stats of training images
`python precalc_stats_perclass.py --root_dataset ~/data/cifar10/images/train/ --dir_dest ~/data/cifar10/fid_stats`
- Compute per-class FID
`python fid_perclass.py --dir_stats ~/data/cifar10/fid_stats --root_samples ~/MSGAN/DCGAN-Mode-Seeking/results/trial/images_test/`

Am I missing something?

For your convenience to track down,
my per-class evaluation code is [here](https://github.com/youngjung/TTUR),
 and preparing training images is [here (cifar10_to_imagefolder.py above)](https://gist.github.com/youngjung/73626bd95d9ce309cd3ba97b963867d3)

**Comment by HelenMao** [comment]
Hi, thanks for your interest in our work.  
In our paper, we use all the training samples and the generated samples in all classes to compute FID (not per-class FID and average the result).
We find most of the previous papers report the FID in this way. 
The mean and the standard derivation are calculated based on five independent trials. Please see the appendix in our paper.

**Comment by youngjung** [comment]
Wow super prompt reply! Thanks!

I misunderstood the sentence in the appendix 'We use all the training samples and the generated samples to compute FID.'. Now I see the point. 5K samples per class and 50K in total and all 50K samples are used to compute a single stats.

(What a waste of time writing per-class FID..... stupid me lol)

Further explanation on five trials is also valuable.
Could you explain whether it means
- five different models from five training trials (probably this one is the right one but just for double check..)
- or five testing for one fixed model (randomness from sampling z from Gaussian)
?

**Comment by HelenMao** [comment]
We just used one fixed model and generated five times of samples. 
Hope it helps.

**Comment by youngjung** [comment]
Thanks!

Finally I got FID of 28.60 from your pretrained model.

However, the model trained by myself reports 35.66.

Did you observe variation among multiple training trials?

I will re-run the training for several times anyway but any comments will be helpful since training for 200K iters takes about 10 hours on my machine.

Is weight_decay on optimizer is accidentally not mentioned in the paper or not erased from your code?
Or, do I have to train for more than 200K iters?

**Comment by HelenMao** [comment]
We just obtained the pre-trained model using the codes released and reported the five times of the results using that model.

**Comment by youngjung** [comment]
Thanks it means that I can keep working on the same code!

 I will train again several times and share my experience.

Thank you again :)

**Comment by youngjung** [comment]
I ran the same code for four more trials and got FIDs below.

trial0: 29.93222174258068
trial1: 30.902965756971412
trial2: 29.98750439731532
trial3: 35.25630393016536

Probably measure of the provided pre-trained model can be reached in a few more trials.

**Comment by HelenMao** [comment]
Hi, I find I set the max_iter=200,000 in my code. In fact, I remembered I trained 200 epochs of the pre-trained model.

**Comment by youngjung** [comment]
Oh, now I see that!

My 00199.pth are not actually from after 200 epoch hahahahaha.

Thanks I will try without `if total_it >= max_it:` block :)
