### ISSUE TITLE
some trouble inDCGAN

### ISSUE THREAD

**Issue by XiaoHao-Chen** [HelenMao/MSGAN#6]
Hi, thanks for such excellent workWhen I ran the DCGAN code you provided, the following error occurred： 
`usage: train.py [-h] --dataroot DATAROOT [--img_size IMG_SIZE] [--nz NZ]
                [--class_num CLASS_NUM] [--phase PHASE]
                [--batch_size BATCH_SIZE] [--nThreads NTHREADS] [--name NAME]
                [--display_dir DISPLAY_DIR] [--result_dir RESULT_DIR]
                [--display_freq DISPLAY_FREQ] [--img_save_freq IMG_SAVE_FREQ]
                [--model_save_freq MODEL_SAVE_FREQ] [--no_display_img]
                [--n_ep N_EP] [--resume RESUME] [--gpu GPU]
train.py: error: the following arguments are required: --dataroot
`
then when I changed the ruquired = True of BaseOptions in options.py to ruquired = False, the error disappeared, but followed by the following error: 
`Traceback (most recent call last):
  File "D:/Python/MSGAN-master/DCGAN-Mode-Seeking/train.py", line 68, in <module>
    main()
  File "D:/Python/MSGAN-master/DCGAN-Mode-Seeking/train.py", line 16, in main
    os.makedirs(opts.dataroot, exist_ok=True)
  File "C:\ProgramData\Anaconda3\lib\os.py", line 205, in makedirs
    head, tail = path.split(name)
  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 204, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType`
 and I tried many ways without correcting the error. So what do you suggest?
Thank you!

**Comment by HelenMao** [comment]
Hi, you need to add your data root path, i.e., --dataroot=your dataset path. please see the readme carefully.

**Comment by XiaoHao-Chen** [comment]
Sorry, I didn't look carefully. It was my fault. Thank you very much for your reply.
